{% set name = "bitstring" %}
{% set version = "3.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a5848a3f63111785224dca8bb4c0a75b62ecdef56a042c8d6be74b16f7e860e7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.2
    - pip
  run:
    - python >=3.2

test:
  imports:
    - bitstring

about:
  home: http://scott-griffiths.github.io/bitstring
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple construction, analysis and modification of binary data.
  doc_url: https://bitstring.readthedocs.io
  dev_url: https://github.com/scott-griffiths/bitstring

extra:
  recipe-maintainers:
    - m-rossi
